# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Tech Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Tech Test
  pod 'Alamofire', '~> 4.7.3'
  pod 'AlamofireObjectMapper', '~> 5.2'
  
end
